import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'rewards': 'Rewards',
      "Welcome back": "Welcome back",
      'quick_actions': 'Quick Actions',
      'missions': 'Missions',
      'invite_friend': 'Invite a friend',
      "Here's your financial snapshot": "Here's your financial snapshot",
      "Overview": "Overview",
      "Documents": "Documents",
      "+12 this month": "+12 this month",
      "Monthly Spending": "Monthly Spending",
      "Active Warranties": "Active Warranties",
      "3 expiring soon": "3 expiring soon",
      "Subscriptions": "Subscriptions",
      "Quick Actions": "Quick Actions",
      "Scan": "Scan",
      "Email": "Email",
      "Bank": "Bank",
      "Phone": "Phone",
      "Recent Activity": "Recent Activity",
      "See All": "See All",
      "Insights": "Insights",
      "Top Category": "Top Category",
      "Shopping": "Shopping",
      "34% of expenses": "34% of expenses",
      "Top Merchant": "Top Merchant",
      "Amazon": "Amazon",
      "23 transactions": "23 transactions",
      "Largest Expense": "Largest Expense",
      "XIUM Level": "XIUM Level",
      'xium_evolving':
          'XIUM is evolving\nAI-powered categorization & smart alerts coming soon',
    },
    'fr_FR': {
      'rewards': 'Récompenses',
      "Documents": "Documents",
      "Welcome back": "Bon retour",
      'quick_actions': 'Actions Rapides',
      'missions': 'Missions',
      'invite_friend': 'Inviter un ami',
      "Here's your financial snapshot": "Voici votre aperçu financier",
      "Overview": "Aperçu",
      "+12 this month": "+12 ce mois-ci",
      "Monthly Spending": "Dépenses Mensuelles",
      "Active Warranties": "Garanties Actives",
      "3 expiring soon": "3 expirent bientôt",
      "Subscriptions": "Abonnements",
      "Quick Actions": "Actions Rapides",
      "Scan": "Scanner",
      "Email": "Email",
      "Bank": "Banque",
      "Phone": "Téléphone",
      "Recent Activity": "Activité Récente",
      "See All": "Voir Tout",
      "Insights": "Connaissances",
      "Top Category": "Catégorie supérieure",
      "Shopping": "Achats",
      "34% of expenses": "34% des dépenses",
      "Top Merchant": "Meilleur Marchand",
      "Amazon": "Amazon",
      "23 transactions": "23 transactions",
      "Largest Expense": "Dépense la plus élevée",
      "XIUM Level": "Niveau XIUM",
      'xium_evolving':
          'XIUM évolue\nCatégorisation intelligente & alertes intelligentes bientôt disponibles',
    },
  };
}
