import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'rewards': 'Rewards',
      "Welcome back": "Welcome back",
      'quick_actions': 'Quick Actions',
      'missions': 'Missions',
      'invite_friend': 'Invite a friend',
      "Here's your financial snapshot": "Here's your financial snapshot",
      "Overview": "Overview",
      "Documents": "Documents",
      "+12 this month": "+12 this month",
      "Monthly Spending": "Monthly Spending",
      "Active Warranties": "Active Warranties",
      "3 expiring soon": "3 expiring soon",
      "Subscriptions": "Subscriptions",
      "Quick Actions": "Quick Actions",
      "Scan": "Scan",
      "Email": "Email",
      "Bank": "Bank",
      "Phone": "Phone",
      "Recent Activity": "Recent Activity",
      "See All": "See All",
      "Insights": "Insights",
      "Top Category": "Top Category",
      "Shopping": "Shopping",
      "34% of expenses": "34% of expenses",
      "Top Merchant": "Top Merchant",
      "Amazon": "Amazon",
      "23 transactions": "23 transactions",
      "Largest Expense": "Largest Expense",
      "XIUM Level": "XIUM Level",
      'xium_evolving':
          'XIUM is evolving\nAI-powered categorization & smart alerts coming soon',
      "Your Stores": "Your Stores",
      "Select a store to view all your related documents.":
          "Select a store to view all your related documents.",
      "Search a store": "Search a store",
      "No stores found": "No stores found",
      "Select Image Source": "Select Image Source",
      "Camera": "Camera",
      "Gallery": "Gallery",
      "Scan your invoice | receipt | warranty  to help XIUM detect documents.":
          "Scan your invoice | receipt | warranty  to help XIUM detect documents.",
      "Position your documents inside the frame.":
          "Position your documents inside the frame.",
      "If the store is not recognized, you can select it manually.":
          "If the store is not recognized, you can select it manually.",
      "Uploading Image": "Uploading Image",
      "Please wait while we process your document.":
          "Please wait while we process your document.",
      "Rewards": "Rewards",
      "Track your points, missions & benefits":
          "Track your points, missions & benefits",
      "Total XIUM Points": "Total XIUM Points",
      "Intermediate": "Intermediate",
      "760 more points to reach the next level":
          "760 more points to reach the next level",
      "Scan a document": "Scan a document",
      "Import a doc from email": "Import a doc from email",
      "Import a doc from bank": "Import a doc from bank",
      "User Status": "User Status",
      "Current Level": "Current Level",
      "Beginner": "Beginner",
      "Your level evolves based on your activity within the application.":
          "Your level evolves based on your activity within the application.",
      "Possible Benefits": "Possible Benefits",
      "Point bonuses on each activity": "Point bonuses on each activity",
      "Early access to certain features": "Early access to certain features",
      "Priority status during new updates":
          "Priority status during new updates",
      "Profile & Setting": "Profile & Setting",
      "User Information": "User Information",
      "Connections & Integrations": "Connections & Integrations",
      "Loyalty": "Loyalty",
      "Connected": "Connected",
      "Not Connected": "Not Connected",
      "Manage Connection": "Manage Connection",
      "Application Settings": "Application Settings",
      "Language": "Language",
      "Terms of Service": "Terms of Service",
      "Privacy Policy": "Privacy Policy",
      "Security": "Security",
      "Logout": "Logout",
    },
    'fr_FR': {
      'rewards': 'Récompenses',
      "Documents": "Documents",
      "Welcome back": "Bon retour",
      'quick_actions': 'Actions Rapides',
      'missions': 'Missions',
      'invite_friend': 'Inviter un ami',
      "Here's your financial snapshot": "Voici votre aperçu financier",
      "Overview": "Aperçu",
      "+12 this month": "+12 ce mois-ci",
      "Monthly Spending": "Dépenses Mensuelles",
      "Active Warranties": "Garanties Actives",
      "3 expiring soon": "3 expirent bientôt",
      "Subscriptions": "Abonnements",
      "Quick Actions": "Actions Rapides",
      "Scan": "Scanner",
      "Email": "Email",
      "Bank": "Banque",
      "Phone": "Téléphone",
      "Recent Activity": "Activité Récente",
      "See All": "Voir Tout",
      "Insights": "Connaissances",
      "Top Category": "Catégorie supérieure",
      "Shopping": "Achats",
      "34% of expenses": "34% des dépenses",
      "Top Merchant": "Meilleur Marchand",
      "Amazon": "Amazon",
      "23 transactions": "23 transactions",
      "Largest Expense": "Dépense la plus élevée",
      "XIUM Level": "Niveau XIUM",
      'xium_evolving':
          'XIUM évolue\nCatégorisation intelligente & alertes intelligentes bientôt disponibles',
      "Your Stores": "Vos Magasins",
      "Select a store to view all your related documents.":
          "Sélectionnez un magasin pour voir tous vos documents liés.",
      "Search a store": "Rechercher un magasin",
      "No stores found": "Aucun magasin trouvé",
      "Select Image Source": "Sélectionnez la source de l'image",
      "Camera": "Caméra",
      "Gallery": "Galerie",
      "Scan your invoice | receipt | warranty  to help XIUM detect documents.":
          "Scannez votre facture | reçu | garantie pour aider XIUM à détecter les documents.",
      "Position your documents inside the frame.":
          "Positionnez vos documents à l'intérieur du cadre.",
      "If the store is not recognized, you can select it manually.":
          "Si le magasin n'est pas reconnu, vous pouvez le sélectionner manuellement.",
      "Uploading Image": "Téléchargement de l'image",
      "Please wait while we process your document.":
          "Veuillez patienter pendant que nous traitons votre document.",
      "Rewards": "Récompenses",
      "Track your points, missions & benefits":
          "Suivez vos points, missions et avantages",
      "Total XIUM Points": "Total de points XIUM",
      "Intermediate": "Intermédiaire",
      "760 more points to reach the next level":
          "760 points de plus pour atteindre le niveau suivant",
      "Scan a document": "Scanner un document",
      "Import a doc from email": "Importer un document depuis l'email",
      "Import a doc from bank": "Importer un document depuis la banque",
      "User Status": "Statut de l'utilisateur",
      "Current Level": "Niveau actuel",
      "Beginner": "Débutant",
      "Your level evolves based on your activity within the application.":
          "Votre niveau évolue en fonction de votre activité au sein de l'application.",
      "Possible Benefits": "Avantages possibles",
      "Point bonuses on each activity": "Bonus de points sur chaque activité",
      "Early access to certain features":
          "Accès anticipé à certaines fonctionnalités",
      "Priority status during new updates":
          "Statut prioritaire lors des nouvelles mises à jour",
      "Profile & Setting": "Profile & Setting",
      "User Information": "User Information",
      "Connections & Integrations": "Connexions & Intégrations",
      "Loyalty": "Fidélité",
      "Connected": "Connecté",
      "Not Connected": "Non connecté",
      "Manage Connection": "Gérer la connexion",
      "Application Settings": "Paramètres de l'application",
      "Language": "Langue",
      "Terms of Service": "Conditions d'utilisation",
      "Privacy Policy": "Politique de confidentialité",
      "Security": "Sécurité",
      "Logout": "Se déconnecter",
    },
  };
}
