// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSmAVwgbes1G5Q9TFi8dMt1JiMHslq9dA',
    appId: '1:88696399302:android:fdc84954d1b7c8decdfec7',
    messagingSenderId: '88696399302',
    projectId: 'xium-app',
    storageBucket: 'xium-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNipTfCf-hiN3p6EGclabqULqvejpK3wU',
    appId: '1:88696399302:ios:d9eacc2c4b2f2373cdfec7',
    messagingSenderId: '88696399302',
    projectId: 'xium-app',
    storageBucket: 'xium-app.firebasestorage.app',
    androidClientId: '88696399302-779skfq83trb3clf0as9k73dj3tstlts.apps.googleusercontent.com',
    iosClientId: '88696399302-k342n00vh88m6pvloc57561gevua3t3r.apps.googleusercontent.com',
    iosBundleId: 'com.enzo.xiumApp',
  );
}
